In [1]:
#
# Pandas tutorial - 3
#
# @author becxer
# @email becxer87@gmail.com
#
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

print ("modules successfully imported")

modules successfully imported


In [2]:
# IRIS 데이터를 불러온다
# IRIS 는 세가지꽃 (Sentosa, Versicolor, Virginica) 에 대한 꽃잎, 꽃받침 에 대한 측정 데이터 이다.
# 참조 -> https://en.wikipedia.org/wiki/Iris_flower_data_set
#
data = pd.read_csv('sample_data/iris/iris.csv')
data.head()

species  sepal_length  sepal_width  petal_length  petal_width
0        0           4.9          3.0           1.4          0.2
1        1           6.2          2.2           4.5          1.5
2        2           6.7          2.5           5.8          1.8
3        0           5.1          3.8           1.9          0.4
4        1           6.0          2.7           5.1          1.6

In [5]:
# 데이터의 상관관계 구하기
data.corr()

species  sepal_length  sepal_width  petal_length  petal_width
species       1.000000      0.782561    -0.419446      0.949043     0.956464
sepal_length  0.782561      1.000000    -0.109369      0.871754     0.817954
sepal_width  -0.419446     -0.109369     1.000000     -0.420516    -0.356544
petal_length  0.949043      0.871754    -0.420516      1.000000     0.962757
petal_width   0.956464      0.817954    -0.356544      0.962757     1.000000

In [6]:
# 데이터의 공분산 구하기
data.cov()

species  sepal_length  sepal_width  petal_length  petal_width
species       0.671141      0.530872    -0.148993      1.371812     0.597987
sepal_length  0.530872      0.685694    -0.039268      1.273682     0.516904
sepal_width  -0.148993     -0.039268     0.188004     -0.321713    -0.117981
petal_length  1.371812      1.273682    -0.321713      3.113179     1.296387
petal_width   0.597987      0.516904    -0.117981      1.296387     0.582414

In [19]:
# 요소별 상관관계 확인을 위한 Onehot encoding
data["sentosa"] = data.species.map(lambda x :  1 if x == 0 else 0)
data["versicolor"] = data.species.map(lambda x :  1 if x == 1 else 0)
data["virginica"] = data.species.map(lambda x : 1 if x == 2 else 0)
data.head()

species  sepal_length  sepal_width  petal_length  petal_width  sentosa  \
0        0           4.9          3.0           1.4          0.2        1   
1        1           6.2          2.2           4.5          1.5        0   
2        2           6.7          2.5           5.8          1.8        0   
3        0           5.1          3.8           1.9          0.4        1   
4        1           6.0          2.7           5.1          1.6        0   

   versicolor  virginica  
0           0          0  
1           1          0  
2           0          1  
3           0          0  
4           1          0

In [33]:
# Sentosa 꽃의 상관관계 확인
data[['sentosa','sepal_length','sepal_width','petal_length','petal_width']].corr()

sentosa  sepal_length  sepal_width  petal_length  petal_width
sentosa       1.000000     -0.717416     0.595601     -0.922688    -0.887510
sepal_length -0.717416      1.000000    -0.109369      0.871754     0.817954
sepal_width   0.595601     -0.109369     1.000000     -0.420516    -0.356544
petal_length -0.922688      0.871754    -0.420516      1.000000     0.962757
petal_width  -0.887510      0.817954    -0.356544      0.962757     1.000000

In [36]:
# 모든 꽃의 상관관계
data.cov()

species  sepal_length  sepal_width  petal_length  petal_width  \
species       0.671141      0.530872    -0.148993      1.371812     0.597987   
sepal_length  0.530872      0.685694    -0.039268      1.273682     0.516904   
sepal_width  -0.148993     -0.039268     0.188004     -0.321713    -0.117981   
petal_length  1.371812      1.273682    -0.321713      3.113179     1.296387   
petal_width   0.597987      0.516904    -0.117981      1.296387     0.582414   
sentosa      -0.335570     -0.280984     0.122148     -0.770022    -0.320358   
versicolor    0.000000      0.031096    -0.095302      0.168233     0.042729   
virginica     0.335570      0.249888    -0.026846      0.601790     0.277629   

               sentosa  versicolor  virginica  
species      -0.335570    0.000000   0.335570  
sepal_length -0.280984    0.031096   0.249888  
sepal_width   0.122148   -0.095302  -0.026846  
petal_length -0.770022    0.168233   0.601790  
petal_width  -0.320358    0.042729   0.277629  
sentosa       0.223714   -0.111857  -0.111857  
versicolor   -0.111857    0.223714  -0.111857  
virginica    -0.111857   -0.111857   0.223714

In [30]:
# SVD (Singular Vector Decomposition) 을 위해 Numpy로 추출해보자
data_feature_only = data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
feat_mat = data_feature_only.as_matrix()
feat_mat[:4]

array([[ 4.9,  3. ,  1.4,  0.2],
       [ 6.2,  2.2,  4.5,  1.5],
       [ 6.7,  2.5,  5.8,  1.8],
       [ 5.1,  3.8,  1.9,  0.4]])

In [56]:
# SVD로는 sigma Eigen-Matrix 를 구할 수 있는데,
# 이것은 각 축의 분산도를 뜯한다.
# 분산도가 낮다는것은 -> 정보가 획일화 되어있음을 나타내므로 그 축은 지워도 정보 손실이 적다!
# 차원 축소가 가능함

U, s, Vh = np.linalg.svd(feat_mat, full_matrices=False)
print "eigen-matrix : ",s
print "4번째 축은 별로 쓸모가 없음, 따라서 없앤다 s[3] = 0"
s[3] = 0

# SVD로 쪼갯던 것을 다시 합쳐본다.
print "\nAfter delete lower eigen - value :\n"
new_a = np.dot(U, np.dot(np.diag(s), Vh))
print(new_a[:4])

eigen-matrix :  [ 95.95066751  17.72295328   3.46929666   1.87891236]
4번째 축은 별로 쓸모가 없음, 따라서 없앤다 s[3] = 0

After delete lower eigen - value :

[[ 4.86832748  3.03145595  1.44707719  0.12665612]
 [ 6.11631145  2.2831163   4.62439242  1.30620289]
 [ 6.72465136  2.4755172   5.76335887  1.85708503]
 [ 5.1598285   3.7405806   1.81107252  0.53854452]]
