In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('sample_data/iris/iris.csv')

In [2]:
#IRIS 데이터를 원-핫 인코딩으로 바꾸기
data_iris = data.as_matrix()
label = data_iris[:,[0]]
mat = data_iris[:,[1,2,3,4]]

In [3]:
#데이터를 학습용과 테스트용으로 나누기
train_mat = mat[:130]
train_label = label[:130]
test_mat = mat[130:]
test_label = label[130:]

print train_mat.shape
print train_label.shape
print test_mat.shape
print test_label.shape

(130, 4)
(130, 1)
(20, 4)
(20, 1)


In [4]:
#파이트레인으로 학습시키기
from pytrain.Kmeans import Kmeans

In [8]:
kmeans = Kmeans(train_mat, dist_func = 'euclidean')

# finding cluster (Fixed K)
cluster_point_fixed = kmeans.cluster(K = 3, epoch = 30)
print("고정된 K 갯수 : " + str(len(cluster_point_fixed)))
print("클러스터 중심점 : \n" + str(cluster_point_fixed))

# Auto finding good cluster (Flexible K)
cluster_point_flexible = kmeans.fit(max_K = 7, random_try_count = 10, epoch = 30)
print("유연한 K 찾은 클러스터 갯수 : " + str(len(cluster_point_flexible)))
print("클러스터 중심점 : \n" + str(cluster_point_flexible))

고정된 K 갯수 : 3
클러스터 중심점 : 
[[ 4.98695652  3.35652174  1.5326087   0.2826087 ]
 [ 6.32142857  2.88809524  4.96785714  1.71071429]
 [ 7.53455556  2.62700546  1.80688314  2.31114885]]
유연한 K 찾은 클러스터 갯수 : 2
클러스터 중심점 : 
[[ 4.98695652  3.35652174  1.5326087   0.2826087 ]
 [ 6.32142857  2.88809524  4.96785714  1.71071429]]
