In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('./iris.csv')

In [2]:
data_iris = data.as_matrix()
label_d = data_iris[:,[0]]
mat = data_iris[:,[1,2,3,4]]

label = []

for idx, l in enumerate(label_d):
    tmp = [0,0,0]
    tmp[int(l[0])] = 1
    label.append(tmp)
label = np.array(label)
print label

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 

In [3]:
train_mat = mat[:130]
train_label = label[:130]
test_mat = mat[130:]
test_label = label[130:]

print train_mat.shape
print train_label.shape
print test_mat.shape
print test_label.shape

(130, 4)
(130, 3)
(20, 4)
(20, 3)


In [4]:
from pytrain.NeuralNetwork import FNN

In [5]:
hidden_layer = [3,3]
fnn = FNN(train_mat,train_label,hidden_layer)
fnn.fit(lr = 0.01, epoch = 1000, err_th = 0.001, batch_size = 30)

In [7]:
print "예측 : ", np.argmax(fnn.predict(test_mat[0])), "답 : ", np.argmax(test_label[0])
print "예측 : ", np.argmax(fnn.predict(test_mat[1])), "답 : ", np.argmax(test_label[1])
print "예측 : ", np.argmax(fnn.predict(test_mat[2])), "답 : ", np.argmax(test_label[2])
print "예측 : ", np.argmax(fnn.predict(test_mat[3])), "답 : ", np.argmax(test_label[3])
print "예측 : ", np.argmax(fnn.predict(test_mat[4])), "답 : ", np.argmax(test_label[4])
print "예측 : ", np.argmax(fnn.predict(test_mat[5])), "답 : ", np.argmax(test_label[5])
print "예측 : ", np.argmax(fnn.predict(test_mat[6])), "답 : ", np.argmax(test_label[6])
print "예측 : ", np.argmax(fnn.predict(test_mat[7])), "답 : ", np.argmax(test_label[7])
print "예측 : ", np.argmax(fnn.predict(test_mat[8])), "답 : ", np.argmax(test_label[8])
print "예측 : ", np.argmax(fnn.predict(test_mat[9])), "답 : ", np.argmax(test_label[9])
print "예측 : ", np.argmax(fnn.predict(test_mat[10])), "답 : ", np.argmax(test_label[10])
print "예측 : ", np.argmax(fnn.predict(test_mat[11])), "답 : ", np.argmax(test_label[11])
print "예측 : ", np.argmax(fnn.predict(test_mat[12])), "답 : ", np.argmax(test_label[12])
print "예측 : ", np.argmax(fnn.predict(test_mat[13])), "답 : ", np.argmax(test_label[13])
print "예측 : ", np.argmax(fnn.predict(test_mat[14])), "답 : ", np.argmax(test_label[14])
print "예측 : ", np.argmax(fnn.predict(test_mat[15])), "답 : ", np.argmax(test_label[15])
print "예측 : ", np.argmax(fnn.predict(test_mat[16])), "답 : ", np.argmax(test_label[16])
print "예측 : ", np.argmax(fnn.predict(test_mat[17])), "답 : ", np.argmax(test_label[17])
print "예측 : ", np.argmax(fnn.predict(test_mat[18])), "답 : ", np.argmax(test_label[18])
print "예측 : ", np.argmax(fnn.predict(test_mat[19])), "답 : ", np.argmax(test_label[19])

예측 :  1 답 :  1
예측 :  2 답 :  2
예측 :  0 답 :  0
예측 :  1 답 :  1
예측 :  2 답 :  2
예측 :  0 답 :  0
예측 :  1 답 :  1
예측 :  2 답 :  2
예측 :  0 답 :  0
예측 :  1 답 :  1
예측 :  2 답 :  2
예측 :  0 답 :  0
예측 :  1 답 :  1
예측 :  2 답 :  2
예측 :  0 답 :  0
예측 :  1 답 :  1
예측 :  2 답 :  2
예측 :  0 답 :  0
예측 :  1 답 :  1
예측 :  2 답 :  2
