In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('../sample_data/iris/iris.csv')

In [3]:
#iris 데이터를 원_핫 인코딩으로 바꾸기
data_iris = data.as_matrix()
label = data_iris[:,[0]]
mat = data_iris[:,[1,2,3,4]]

In [4]:
train_mat = mat[:130]
train_label = label[:130]
test_mat = mat[130:]
test_label = label[130:]

print train_mat.shape
print train_label.shape
print test_mat.shape
print test_label.shape

(130, 4)
(130, 1)
(20, 4)
(20, 1)


In [12]:
from pytrain.Kmeans import Kmeans

In [16]:
kmeans = Kmeans(train_mat,dist_func='euclidean')

cluster_point_fixed = kmeans.cluster(K = 3, epoch = 30)
print("고정된 k 갯수 :" +str(len(cluster_point_fixed)))
print("클러스터 중심점 : \n" + str(cluster_point_fixed))

cluster_point_flexible = kmeans.fit(max_K =7 , random_try_count = 10, epoch=30)
print("유연한 k 차즌 클러스터 갯수 :" + str(len(cluster_point_flexible)))
print("클러스터 중심점 : \n"+ str(cluster_point_flexible))

고정된 k 갯수 :3
클러스터 중심점 : 
[[ 4.98636364  3.39772727  1.45909091  0.24772727]
 [ 5.95660377  2.77358491  4.43584906  1.46037736]
 [ 6.82727273  3.04545455  5.71212121  2.07272727]]
유연한 k 차즌 클러스터 갯수 :2
클러스터 중심점 : 
[[ 4.98695652  3.35652174  1.5326087   0.2826087 ]
 [ 6.32142857  2.88809524  4.96785714  1.71071429]]


In [5]:
from pytrain.KNN import KNN


In [6]:
K = 5
knn = KNN(train_mat, train_label, K, 'manhattan')

In [10]:
print "예측 :", knn.predict(test_mat[2]),",답 : ", test_label[2]
print "에측 :", knn.predict(test_mat[0]),",답 : ", test_label[0]
print "에측 :", knn.predict(test_mat[1]),",답 : ", test_label[1]
print "에측 :", knn.predict(test_mat[12]),",답 : ", test_label[12]

 예측 :

TypeError: 'NoneType' object is not callable